-- AlterTable
ALTER TABLE "AutomationMetaUsage" ADD COLUMN     "callCountPct" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cpuTimePct" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalTimePct" DOUBLE PRECISION NOT NULL DEFAULT 0;
