-- AlterTable
ALTER TABLE "Ad" ADD COLUMN     "video100" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "video3s" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "videoPlay" DOUBLE PRECISION DEFAULT 0;

-- AlterTable
ALTER TABLE "AdSet" ADD COLUMN     "video100" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "video3s" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "videoPlay" DOUBLE PRECISION DEFAULT 0;

-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN     "video100" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "video3s" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "videoPlay" DOUBLE PRECISION DEFAULT 0;
