-- AlterTable
ALTER TABLE "Ad" ADD COLUMN     "holdRate" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "hookRate" DOUBLE PRECISION DEFAULT 0;

-- AlterTable
ALTER TABLE "AdSet" ADD COLUMN     "holdRate" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "hookRate" DOUBLE PRECISION DEFAULT 0;

-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN     "holdRate" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "hookRate" DOUBLE PRECISION DEFAULT 0;
